export const HOUSES = {
  gryffindor: {
    name: 'Gryffindor',
    accent: '#c8102e',
    accent2: '#eeba30',
    glow: 'rgba(238, 186, 48, 0.55)',
    particle: 'embers',
    cursor: 'embers',
    tagline: 'Where courage lights the way.',
    description: 'A house for brave hearts who choose action when the path gets dark.',
    traits: ['Bravery', 'Nerve', 'Chivalry'],
    commonRoom: 'Gryffindor Tower',
    entryLabel: 'Enter Gryffindor Tower',
    emblem: 'Lion',
    welcomeQuote: 'Ah... a brave soul has arrived.',
    welcomeLines: [
      'The Sorting Hat has chosen your path, and today you step into the legendary halls of Gryffindor House.',
      'Here, courage is your strength.',
      'Here, bravery shapes your destiny.',
      'Here, every adventure begins.',
    ],
    blessingLines: [
      'May your heart remain fearless.',
      'May your choices inspire others.',
      'And may your story become Hogwarts legend.',
    ],
    silhouette: 'none',
    logo: '/images/house1.png',
  },
  slytherin: {
    name: 'Slytherin',
    accent: '#1a472a',
    accent2: '#aaaaaa',
    glow: 'rgba(94, 189, 138, 0.45)',
    particle: 'smoke',
    cursor: 'smoke',
    tagline: 'Ambition coiled in shadow.',
    description: 'A house for sharp minds who turn pressure into power and strategy.',
    traits: ['Ambition', 'Cunning', 'Resourcefulness'],
    commonRoom: 'Dungeons beneath the lake',
    entryLabel: 'Enter the Slytherin Common Room',
    emblem: 'Serpent',
    welcomeQuote: 'Ah... ambition burns quietly within you.',
    welcomeLines: [
      'The Sorting Hat has chosen your path, and today you enter the shadowed strength of Slytherin House.',
      'Here, ambition is your compass.',
      'Here, strategy shapes your destiny.',
      'Here, power learns patience.',
    ],
    blessingLines: [
      'May your mind remain sharp.',
      'May your choices open hidden doors.',
      'And may your name echo through Hogwarts legend.',
    ],
    silhouette: 'snake',
    logo: '/images/house2.png',
  },
  ravenclaw: {
    name: 'Ravenclaw',
    accent: '#0e1a40',
    accent2: '#946b2d',
    glow: 'rgba(94, 140, 222, 0.5)',
    particle: 'stars',
    cursor: 'stars',
    tagline: 'Wit beyond measure.',
    description: 'A house for curious thinkers who chase ideas beyond the obvious answer.',
    traits: ['Wisdom', 'Wit', 'Creativity'],
    commonRoom: 'Ravenclaw Tower',
    entryLabel: 'Enter Ravenclaw Tower',
    emblem: 'Eagle',
    welcomeQuote: 'Ah... a curious mind has arrived.',
    welcomeLines: [
      'The Sorting Hat has chosen your path, and today you climb into the brilliant halls of Ravenclaw House.',
      'Here, wisdom is your lantern.',
      'Here, wit shapes your destiny.',
      'Here, every question becomes an adventure.',
    ],
    blessingLines: [
      'May your thoughts remain bright.',
      'May your choices reveal new worlds.',
      'And may your ideas become Hogwarts legend.',
    ],
    silhouette: 'books',
    logo: '/images/house3.png',
  },
  hufflepuff: {
    name: 'Hufflepuff',
    accent: '#ecb939',
    accent2: '#372e29',
    glow: 'rgba(255, 200, 90, 0.55)',
    particle: 'fireflies',
    cursor: 'fireflies',
    tagline: 'Loyalty, warm as candlelight.',
    description: 'A house for steady souls who build trust through patience and kindness.',
    traits: ['Loyalty', 'Patience', 'Fairness'],
    commonRoom: 'Near the kitchens',
    entryLabel: 'Enter the Hufflepuff Common Room',
    emblem: 'Badger',
    welcomeQuote: 'Ah... a loyal heart has arrived.',
    welcomeLines: [
      'The Sorting Hat has chosen your path, and today you enter the warm halls of Hufflepuff House.',
      'Here, kindness is your strength.',
      'Here, loyalty shapes your destiny.',
      'Here, every friendship becomes magic.',
    ],
    blessingLines: [
      'May your heart remain steady.',
      'May your choices bring comfort to others.',
      'And may your goodness become Hogwarts legend.',
    ],
    silhouette: 'lantern',
    logo: '/images/house4.png',
  },
};

export const HOUSE_IDS = Object.keys(HOUSES);
